package:
  name: pyparallelproj
  version: {{ environ.get('GIT_DESCRIBE_TAG','v')[1:] }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.7
  run:
    - python >=3.7
    - pip
    - setuptools-scm
    - setuptools_scm_git_archive
    - parallelproj >=1.1.2
    - numpy >=1.18
    - matplotlib >=3.2.1
    - numba >=0.49
    - scipy >=1.2

about:
  home: https://github.com/gschramm/pyparallelproj
  license:  MIT License
  summary: 'parallelized TOF PET projectors'
