name: parallelproj

channels:
  - conda-forge

dependencies:
  - parallelproj>=1.5
  - matplotlib>=3.2.1
  - pydantic>=1.10
  - scipy>=1.2
  - nibabel
  - h5py
  - pandas
  - seaborn

  # optional for pytorch exampler:
  # - pytorch
  # - dill
